# Build stage
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
ENV MAVEN_OPTS="-Xmx300m"
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
